@startuml
title Smart Home Monolith Diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

top to bottom direction

Person(customer, "Клиент", "Пользователь")
Person(support, "Сотрудник", "Тех.поддержка")

Enterprise_Boundary(monolith, "Smart Home") {
    Container(UIContainer, "WebPage", "JavaScript/HTML")

    System_Boundary(heatingSystem, "Домен: Отопление") {
        Container(heatingContainer, "Дашборд отопления", "Java", "Управление температурой / мониторинг")

    }
    System_Boundary(deviceSystem, "Домен: устройства") {
        Container(deviceContainer, "Настройка устройств", "Java", "Включить / выключить, добавить / удалить")
    }
}

System_Ext(heatingDevices, "Отопительное оборудование", "Heating Device")
System_Ext(heatingSensor, "Температурный датчик", "Temperature Sensor")

Rel(customer, UIContainer, "Взаимодействие с системой")
Rel(support, UIContainer, "Настройка системы")
Rel(UIContainer, heatingContainer, "Получаем данные для дашборда / устанавливаем температуру", "GET/POST HTTP, JSON")
Rel(UIContainer, deviceContainer, "Подключаем / удаляем устройства", "PUT/DELETE HTTP, JSON")

Rel(heatingContainer, heatingDevices, "", "HTTP, Binary data")
Rel(heatingContainer, heatingSensor, "", "HTTP, Binary data")
Rel(deviceContainer, heatingDevices, "", "HTTP, Binary data")
Rel(deviceContainer, heatingSensor, "", "HTTP, Binary data")

@enduml